# use container-based Ubuntu Trusty
dist: bionic
sudo: true

language: python
python:
  - "3.6.8"

services:
  - docker

install:
  - pip install -U pip==20.2.2 setuptools==49.6.0
  - pip install poetry
  - poetry install

script:
  - poetry run flake8
